"""Curated Bengaluru racquet-sport facilities supplied for CourtMate discovery."""

BENGALURU_FACILITIES = [
    {"id": "krishna-premier-vijayanagar", "name": "Krishna Premier Badminton Academy", "sport": "badminton", "area": "Vijayanagar", "phone": "+91 80 4012 4828", "booking_method": "Phone / direct contact"},
    {"id": "krishna-premier-koramangala", "name": "Krishna Premier Badminton Arena", "sport": "badminton", "area": "Koramangala", "phone": "+91 91139 96250", "booking_method": "Phone / direct contact"},
    {"id": "citi-nest-indiranagar", "name": "Citi Nest Sports Centre", "sport": "badminton", "area": "Indiranagar", "phone": "+91 99454 77660", "booking_method": "Playo", "booking_url": "https://playo.co/venues/bangalore/sports/badminton"},
    {"id": "nagarbhavi-sports-arena", "name": "Nagarbhavi Sports Arena", "sport": "badminton", "area": "Nagarbhavi", "phone": "+91 89042 47968", "booking_method": "Phone / direct contact"},
    {"id": "6s-badminton-arena", "name": "6S Badminton Arena", "sport": "badminton", "area": "Armane Nagar", "phone": "+91 91872 02665", "booking_method": "Phone / Playo", "booking_url": "https://playo.co/venues/bangalore/sports/badminton"},
    {"id": "kba-badminton", "name": "Karnataka Badminton Association", "sport": "badminton", "area": "Vasanth Nagar", "phone": "+91 80 4278 8888", "booking_method": "Phone / membership"},
    {"id": "rajkumar-badminton", "name": "Dr. Rajkumar Badminton Academy", "sport": "badminton", "area": "Rajajinagar", "phone": "+91 80 3570 1888", "booking_method": "Phone / Playo", "booking_url": "https://playo.co/venues/bangalore/sports/badminton"},
    {"id": "namma-shuttle-badminton", "name": "Namma Shuttle", "sport": "badminton", "area": "HSR Layout", "phone": "+91 81234 68333", "booking_method": "Playo", "booking_url": "https://playo.co/venues/bangalore/sports/badminton"},
    {"id": "racketlon-badminton", "name": "Racketlon Sports Academy", "sport": "badminton", "area": "Bilekahalli", "phone": "+91 78997 92291", "booking_method": "Playo", "booking_url": "https://playo.co/venues/bangalore/sports/badminton"},
    {"id": "play-mania-badminton", "name": "Play Mania Sports Lounge", "sport": "badminton", "area": "Bellandur", "phone": "+91 94487 90559", "booking_method": "Playo", "booking_url": "https://playo.co/venues/bangalore/sports/badminton"},
    {"id": "majesstine-badminton", "name": "The Majesstine Sports", "sport": "badminton", "area": "HSR Layout", "phone": "+91 63644 44441", "booking_method": "Phone / online"},
    {"id": "kslta-tennis", "name": "Karnataka State Lawn Tennis Association", "sport": "tennis", "area": "Cubbon Park", "phone": "+91 80 2286 9797", "booking_method": "Phone / membership"},
    {"id": "tennis-temple", "name": "Tennis Temple", "sport": "tennis", "area": "Rajajinagar", "phone": "+91 74065 59000", "booking_method": "Phone / direct contact"},
    {"id": "prestige-shantiniketan-tennis", "name": "Tennis Court, Prestige Shantiniketan", "sport": "tennis", "area": "Hoodi", "booking_method": "Residents only"},
    {"id": "dhi-tennis", "name": "DHI Sports", "sport": "tennis", "area": "Bannerghatta Road", "phone": "+91 97422 20232", "booking_method": "Phone / app"},
    {"id": "game-theory-indiranagar-squash", "name": "Game Theory - 100 Feet Road", "sport": "squash", "area": "Indiranagar", "phone": "+91 81978 97462", "booking_method": "Game Theory app"},
    {"id": "game-theory-koramangala-squash", "name": "Game Theory Koramangala NGV", "sport": "squash", "area": "Koramangala", "booking_method": "App / Playtomic", "booking_url": "https://playtomic.io"},
    {"id": "kba-squash", "name": "Karnataka Badminton Association", "sport": "squash", "area": "Vasanth Nagar", "phone": "+91 80 4278 8888", "booking_method": "Phone / membership"},
    {"id": "bangalore-club-squash", "name": "Bangalore Club Squash Courts", "sport": "squash", "area": "Ashok Nagar", "phone": "+91 94452 32233", "booking_method": "Members only"},
    {"id": "lakshyan-squash", "name": "Lakshyan Academy of Sports", "sport": "squash", "area": "Sarjapur", "phone": "+91 70223 14523", "booking_method": "Phone / direct contact"},
    {"id": "ace-champion-tt", "name": "ACE Champion Table Tennis Academy", "sport": "table_tennis", "area": "Girinagar / Banashankari", "phone": "+91 81976 36633", "booking_method": "Phone / direct contact"},
    {"id": "top-spin-tt", "name": "Top Spin Table Tennis Academy", "sport": "table_tennis", "area": "J.P. Nagar", "phone": "+91 90600 32357", "booking_method": "Phone / direct contact"},
    {"id": "horizon-tt", "name": "Horizon TT Club", "sport": "table_tennis", "area": "Basavanagudi", "phone": "+91 98446 62179", "booking_method": "Phone / direct contact"},
    {"id": "namma-shuttle-tt", "name": "Namma Shuttle", "sport": "table_tennis", "area": "HSR Layout", "phone": "+91 81234 68333", "booking_method": "Playo", "booking_url": "https://playo.co/venues/bangalore/sports/all"},
    {"id": "game-theory-tt", "name": "Game Theory - 100 Feet Road", "sport": "table_tennis", "area": "Indiranagar", "phone": "+91 81978 97462", "booking_method": "Game Theory app"},
    {"id": "padel-pro-whitefield", "name": "Padel Pro Whitefield", "sport": "padel", "area": "Whitefield", "phone": "+91 91872 35219", "booking_method": "Phone / app"},
    {"id": "7padel-hsr", "name": "7Padel | The Courtside HSR", "sport": "padel", "area": "HSR Layout", "phone": "+91 91520 03448", "booking_method": "Phone / app"},
    {"id": "padelsmash", "name": "Padelsmash", "sport": "padel", "area": "Shivaji Nagar", "phone": "+91 99012 27500", "booking_method": "Phone / app"},
    {"id": "pickn-padel", "name": "PicknPadel Arena", "sport": "padel", "area": "Kalyan Nagar / Hennur", "phone": "+91 72044 43707", "booking_method": "Phone / app"},
    {"id": "backyard-padel", "name": "Backyard Sports Club", "sport": "padel", "area": "Kumaraswamy Layout", "phone": "+91 72478 55609", "booking_method": "Phone / direct contact"},
    {"id": "game-theory-padel", "name": "Game Theory Koramangala NGV", "sport": "padel", "area": "Koramangala", "booking_method": "Game Theory app / Playtomic", "booking_url": "https://playtomic.io"},
    {"id": "indian-padel-federation", "name": "Indian Padel Federation - Padel Court", "sport": "padel", "area": "Sadashiva Nagar", "booking_method": "On-site contact"},
    {"id": "prime-pickleball", "name": "Prime Pickleball", "sport": "pickleball", "area": "Sarjapur", "phone": "+91 76660 66272", "booking_method": "Phone / membership"},
    {"id": "swysh-pickleball", "name": "Swysh Pickleball MG Road", "sport": "pickleball", "area": "MG Road", "phone": "+91 63630 96989", "booking_method": "Phone / app"},
    {"id": "pickle-and-play", "name": "Pickle and Play", "sport": "pickleball", "area": "Basavanagudi", "phone": "+91 80505 19168", "booking_method": "App-based booking"},
    {"id": "pickle-panda", "name": "Pickle Panda", "sport": "pickleball", "area": "Hennur", "phone": "+91 87788 51139", "booking_method": "Phone / direct contact"},
    {"id": "pickle-hub", "name": "Pickle Hub", "sport": "pickleball", "area": "Subramanyapura", "phone": "+91 80882 62479", "booking_method": "Phone / direct contact"},
    {"id": "dink-pickleball", "name": "The Dink Pickleball Arena", "sport": "pickleball", "area": "Basaveshwar Nagar", "phone": "+91 99869 46839", "booking_method": "App / phone"},
    {"id": "dhi-pickleball", "name": "DHI Sports", "sport": "pickleball", "area": "Bannerghatta Road", "phone": "+91 97422 20232", "booking_method": "Phone / app"},
]
